kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "foreman.fullname" . }}-websockify-nginx
  labels:
    {{- include "foreman.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;
    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format  main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log  main;
        keepalive_timeout 65;
        server {
            listen 5900;
            listen [::]:5900;

            access_log /var/log/nginx/access.log  main;

            location ~ ^/websockify/([0-9]+)$ {
                proxy_pass https://127.0.0.1:$1;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
            }
        }
    }

